<?php
if($this->error) { ?>
    <ul>
    <?php foreach ($this->error['error'] as $item): ?>
        <li><?= $item?></li>
    <?php endforeach;?>
    </ul>
<?php } ?>

<div class="row">
    <div class="col-md-4 col-md-offset-4">
        <h3 class="text-center">Registration</h3>
        <form method="post" action="/register">
            <div class="form-group">
                <label>Username</label>
                <input type="text" class="form-control" name="username" placeholder="Username">
            </div>
            <div class="form-group">
                <label>Password</label>
                <input type="password" class="form-control" name="password" placeholder="Password">
            </div>
            <div class="form-group">
                <label>Confirm password</label>
                <input type="password" class="form-control" name="confirm_password" placeholder="Confirm password">
            </div>
            <button type="submit" class="btn btn-default">Submit</button>
        </form>
    </div>
</div>